apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: valque/conversao-temperatura:v1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service 
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort